### ISSUE TITLE
hci_le_set_scan_parameters and hci_le_set_scan_enable failed error messages

### ISSUE THREAD

**Issue by rkkhanna** [alexarch21/BLE-detect#4]
Hi Alex, this small project has been working very well for me over the last six months, thanks to your work. To refresh, I am running it on a RPI Zero 2W.
Lately though I have started noticing following errors (_3rd & 4th line below_) in the log file:

> [MQTT] Connecting with broker at tcp://aaa.bbb.cc.dd:pppp...
> [MQTT] OK Connected !
> [BTLE] hci_le_set_scan_parameters failed -1
> [BTLE] hci_le_set_scan_enable failed -1

This usually happens if I kill `bdetect` process using `sudo pkill bdetect`. I have set up systemd service (as root user) to restart `bdetect` anytime the process is killed/not running. Lately I was doing some testing that required me to kill `bdetect` process and check for successful restart because of systemd service. That is when I started noticing above errors after each kill / restart, though it may just be a coincidence.

Though I am not positive, but I think my RPI stops sensing the beacons after above errors. I then have to restart RPI to get it to start working properly again.

Do you mind shedding some light on what these errors mean? And is there a fix I could apply to address the issue, if there is one?

Thank you for your attention and help.

**Comment by alexarch21** [comment]
I've had a similar experience when killing the process, but usually the HCI device will work again after a couple of attempts of restarting the process (without reboot). 

I didn't really dive any deeper into this, as in normal operation the process would not be killed. But from what I remember, the reason is the Bluetooth stack not releasing the HCI device when a process using the BLE API isn't properly releasing the device explicitly (ie when it is killed). Technically this is a bug in the BLE stack, but the whole BLE implementation in BlueZ is pretty sketchy to begin with.

You could try terminating the process with an INT signal instead of a KILL, as the code will correctly shut down the HCI device when it receives SIGINT (but not on KILL).

Both API calls mentioned in your logs above only return a single error value (-1) without details. But there could be more info about the error in `errno`. Printing that after a failed API call could shed some more light on why exactly this happens.

> Though I am not positive, but I think my RPI stops sensing the beacons after above errors.

Correct, the BLE stack will not be operational after these errors. The code should probably handle these errors as critical and terminate the process rather than plowing on.

**Comment by rkkhanna** [comment]
Got it. Will try terminating process with SIGINT instead to see if error reappears. Will test it over the weekend as I left on a business trip today.
Maybe I will experiment with a job to scan log file for these errors after a restart. I can then either put it in a loop to SIGINT and restart, or figure out a way to get a notification to Home Assistant.

If you have other, more elegant solutions would love to hear those from you.

Thank you for your prompt reply and help.

**Comment by rkkhanna** [comment]
> You could try terminating the process with an INT signal instead of a KILL, as the code will correctly shut down the HCI device when it receives SIGINT (but not on KILL).

Hi Alex, you were right regarding killing process using SIGINT. Tried multiple times and each time `bdetect` restarted successfully without HCI errors. 
As you mentioned, there isn't a need to kill the process once it is up and running. It is pretty much set-it and forget-it, but good to know the right way to kill it if need be.

 I will go ahead and close the incident.

Thank you for your help.
